### ISSUE TITLE
Issues with running tests

### ISSUE THREAD

**Issue by rakanalh** [holgerd77/django-dynamic-scraper#48]
Hello,

There are issues when running the tests.

If you use
```
cd tests
./run_tests.sh
```
The following errors will emerge:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rakan/.virtualenvs/dynamic-scraper/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/rakan/.virtualenvs/dynamic-scraper/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rakan/.virtualenvs/dynamic-scraper/lib/python2.7/site-packages/django/core/management/commands/test.py", line 50, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/rakan/.virtualenvs/dynamic-scraper/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/rakan/.virtualenvs/dynamic-scraper/lib/python2.7/site-packages/django/core/management/commands/test.py", line 71, in execute
    super(Command, self).execute(*args, **options)
  File "/Users/rakan/.virtualenvs/dynamic-scraper/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/rakan/.virtualenvs/dynamic-scraper/lib/python2.7/site-packages/django/core/management/commands/test.py", line 88, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/rakan/.virtualenvs/dynamic-scraper/lib/python2.7/site-packages/django/test/runner.py", line 146, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "/Users/rakan/.virtualenvs/dynamic-scraper/lib/python2.7/site-packages/django/test/runner.py", line 66, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'ModelTest'
```

Running 
```
python manage.py test basic
``` 

is all fine. However, running
```
python manage.py test scraper
```
Will result in:
```
======================================================================
ERROR: test_xml_content_type (scraper.scraper_run_test.ScraperRunTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rakan/Work/Python/django-dynamic-scraper/tests/scraper/scraper_test.py", line 155, in setUp
    self.crawler.install()
AttributeError: 'CrawlerProcess' object has no attribute 'install'

----------------------------------------------------------------------
```

This is for all tests in scraper.

**Comment by rakanalh** [comment]
Seems like the other part of this ticket was caused by Scrapy==0.24.4. I've installed version 0.16 to make  it work.

**Comment by rakanalh** [comment]
If i comment out the self.crawler.install(), here's what i get:

```
======================================================================
ERROR: test_static_processor_correct_x_path (scraper.scraper_run_test.ScraperRunTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rakan/Work/Python/django-dynamic-scraper/tests/scraper/scraper_run_test.py", line 284, in test_static_processor_correct_x_path
    self.run_event_spider(1)
  File "/Users/rakan/Work/Python/django-dynamic-scraper/tests/scraper/scraper_test.py", line 83, in run_event_spider
    self.crawler.start()
  File "/Users/rakan/.virtualenvs/dynamic-scraper/lib/python2.7/site-packages/scrapy/crawler.py", line 80, in start
    reactor.run(installSignalHandlers=False) # blocking call
  File "/Users/rakan/.virtualenvs/dynamic-scraper/lib/python2.7/site-packages/twisted/internet/base.py", line 1191, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/Users/rakan/.virtualenvs/dynamic-scraper/lib/python2.7/site-packages/twisted/internet/base.py", line 1171, in startRunning
    ReactorBase.startRunning(self)
  File "/Users/rakan/.virtualenvs/dynamic-scraper/lib/python2.7/site-packages/twisted/internet/base.py", line 683, in startRunning
    raise error.ReactorNotRestartable()
ReactorNotRestartable
```

all over. Is this something wrong with my configuration?

**Comment by holgerd77** [comment]
What self.crawler.install() are you commenting out?
