### ISSUE TITLE
with scrapyd got this error: exceptions.OSError: [Errno 20] Not a directory

### ISSUE THREAD

**Issue by jszsj** [holgerd77/django-dynamic-scraper#50]
Sorry, my English is not very well, but I'm working on it.
I'm flowing the doc to study how to use DDS, everything works fine just before  the 'Scheduling scrapers/checkers' section in the advanced topics, I started scrapyd and deploy the scrapy project to it, then run this command:
```
python manage.py celeryd -l info -B --settings=DjangoScrapy.settings
```

the job runs every 5 minute just as I set in django admin, but I got this error in the terminal window which I start scrapyd:
```
......
2015-08-17 00:03:24+0800 [Launcher,13578/stderr] /Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/dynamic_scraper/pipelines.py:4: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline` is deprecated, use `scrapy.pipelines` instead
	  from scrapy.contrib.pipeline.images import ImagesPipeline
2015-08-17 00:03:24+0800 [Launcher,13578/stderr] /Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/dynamic_scraper/pipelines.py:4: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline.images` is deprecated, use `scrapy.pipelines.images` instead
	  from scrapy.contrib.pipeline.images import ImagesPipeline
2015-08-17 00:03:24+0800 [Launcher,13578/stderr] Unhandled error in Deferred:
2015-08-17 00:03:24+0800 [Launcher,13578/stderr]

Traceback (most recent call last):
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/cmdline.py", line 150, in _run_command
    cmd.run(args, opts)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/crawler.py", line 153, in crawl
    d = crawler.crawl(*args, **kwargs)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/core/engine.py", line 67, in __init__
    self.scraper = Scraper(crawler)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/core/scraper.py", line 70, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/middleware.py", line 34, in from_settings
    mw = mwcls.from_crawler(crawler)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/pipelines/media.py", line 33, in from_crawler
    pipe = cls.from_settings(crawler.settings)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/pipelines/images.py", line 57, in from_settings
    return cls(store_uri)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/dynamic_scraper/pipelines.py", line 15, in __init__
    super(DjangoImagesPipeline,  self).__init__(*args, **kwargs)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/pipelines/files.py", line 160, in __init__
    self.store = self._get_store(store_uri)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/pipelines/files.py", line 181, in _get_store
    return store_cls(uri)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/pipelines/files.py", line 43, in __init__
    self._mkdir(self.basedir)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/site-packages/scrapy/pipelines/files.py", line 72, in _mkdir
    os.makedirs(dirname)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/zhushajun/.pyenv/versions/scrapy_env2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
exceptions.OSError: [Errno 20] Not a directory: '/private/var/folders/32/2_lmw4t55m5fx_gb5v7d_0vr0000gn/T/ScrapyDemo-1439724559-dDctsA.egg/ScrapyDemo'
2015-08-17 00:03:24+0800 [-] Process finished:  project='ScrapyDemo' spider='article_spider' job='51059b61443011e58ecf3c075429eea5' pid=13578 log='logs/ScrapyDemo/article_spider/51059b61443011e58ecf3c075429eea5.log' items='file:///Users/zhushajun/items/ScrapyDemo/article_spider/51059b61443011e58ecf3c075429eea5.jl'
```
(ScrapyDemo is my scrapy project and the django app name)
I'm so confused, and don't know how to fix this,could u please help me to fix this  error? Thanks!

By the way, if I don't know how many pages of a website, does pagination support to scrapy as much pages as it can? Or, is there a solution to check if the page have a 'next page' button, this will scrapy all the pages, that would be very useful to me.

**Comment by holgerd77** [comment]
Hi @jszsj, are you scraping images and did you provide the settings parameter in the Scrapy ``settings.py``file?
See: http://django-dynamic-scraper.readthedocs.org/en/latest/advanced_topics.html#scraping-images-screenshots

About your second question: there is a discussion going on around implementing Scrapy spider rules as a new pagination mechanism, see this issue: https://github.com/holgerd77/django-dynamic-scraper/issues/11

This would make the pagination possible you would like to use. Nothing decided yet though, so if it will be realized within a future release.

Greetings
Holger

**Comment by jszsj** [comment]
I don't need to scraping images by now, and I kept all the settings for scraping images.
I removed the DjangoImagesPipeline from the ITEM_PIPELINES list, and the errors are gone,it works very well.
I don't know what caused that error, I had created a thumbnails folder in the scrapy folder, any idea?

**Comment by holgerd77** [comment]
Hmm, no, actually not. Anyway, great that it works now!
