### ISSUE TITLE
can't run python manage.py celeryd

### ISSUE THREAD

**Issue by ratha-pkh** [holgerd77/django-dynamic-scraper#54]
Trying running $python manage.py celeryd -l info -B --settings=example_project.settings gives me this error:
File "manage.py", line 10, in <module>
TypeError: invalid arguments

My system info as below:
Python 2.7
Celery 3.1.19
Django-celery 3.1.16
Django-celery is installed and can be seen in example_project django admin page except I got issue when running the example command. Any advise would be appreciated. Thanks.

**Comment by holgerd77** [comment]
What do you get on ``python manage.py help celeryd``?

**Comment by ratha-pkh** [comment]
The same error.
```
C:\Python27\lib\site-packages\celery\app\defaults.py:251: CPendingDeprecationWarning:
    The 'BROKER_VHOST' setting is scheduled for deprecation in     version 2.5 and removal in version v4.0.     Use the BROKER_URL setting instead

  alternative='Use the {0.alt} instead'.format(opt))

C:\Python27\lib\site-packages\celery\app\defaults.py:251: CPendingDeprecationWarning:
    The 'BROKER_HOST' setting is scheduled for deprecation in     version 2.5 and removal in version v4.0.     Use the BROKER_URL setting instead

  alternative='Use the {0.alt} instead'.format(opt))

C:\Python27\lib\site-packages\celery\app\defaults.py:251: CPendingDeprecationWarning:
    The 'BROKER_USER' setting is scheduled for deprecation in     version 2.5 and removal in version v4.0.     Use the BROKER_URL setting instead

  alternative='Use the {0.alt} instead'.format(opt))

C:\Python27\lib\site-packages\celery\app\defaults.py:251: CPendingDeprecationWarning:
    The 'BROKER_PASSWORD' setting is scheduled for deprecation in     version 2.5 and removal in version v4.0.     Use the BROKER_URL setting instead

  alternative='Use the {0.alt} instead'.format(opt))

C:\Python27\lib\site-packages\celery\app\defaults.py:251: CPendingDeprecationWarning:
    The 'BROKER_PORT' setting is scheduled for deprecation in     version 2.5 and removal in version v4.0.     Use the BROKER_URL setting instead

  alternative='Use the {0.alt} instead'.format(opt))

C:\Python27\lib\site-packages\django\core\management\base.py:259: RemovedInDjango19Warning: "requires_model_validation" is deprecated in favor of "requires_system_checks".
  RemovedInDjango19Warning)

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 322, in execute
    self.fetch_command(options.args[0]).print_help(self.prog_name, options.args[0])
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 366, in print_help
    parser = self.create_parser(prog_name, subcommand)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 312, in create_parser
    help='Verbosity level; 0=minimal output, 1=normal output, 2=verbose output, 3=very verbose output')
  File "C:\Python27\lib\optparse.py", line 1018, in add_option
    raise TypeError, "invalid arguments"
TypeError: invalid arguments
```

**Comment by holgerd77** [comment]
Hmm, strange. Are you already on ``Django 1.9``?

**Comment by ratha-pkh** [comment]
No, I've installed 1.8 as suggested by the documentation.

**Comment by holgerd77** [comment]
Seems that something in your installation is wrong, don't have really an idea what it is I'm afraid.

**Comment by ratha-pkh** [comment]
It works when I tried django 1,7.1. Actually, don't know what the real issue with django 1.8. Anyway, thanks.

**Comment by Aliiibukhari** [comment]
Could anyone please help me out? I'm getting the same error.

**Comment by Aliiibukhari** [comment]
I need some serious help regarding this, this library is needed for my final year project and i think i am having compatibility issues, could you please help me out?
