### ISSUE TITLE
urlopen error Int or String expected

### ISSUE THREAD

**Issue by yunmanger1** [holgerd77/django-dynamic-scraper#81]
I have python 2.7.3

```
>>> from future import standard_library
>>> standard_library.install_aliases()
>>> from builtins import object
>>> import datetime, json
>>> import urllib.request, urllib.parse, http.client
>>> 
>>> urllib.request.urlopen('http://localhost:6800/listjobs.json?project=default')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ve/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 171, in urlopen
    return opener.open(url, data, timeout)
  File "/ve/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/ve/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/ve/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/ve/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1311, in http_open
    return self.do_open(http_client.HTTPConnection, req)
  File "/ve/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1287, in do_open
    raise URLError(err)
future.backports.urllib.error.URLError: <urlopen error Int or String expected>
```

This is a snippet from `utils/task_utils.py`

```
django-dynamic-scraper==0.11.3
```

**Comment by guettli** [comment]
Just for the records. We had the same error, but coming from the module selenium. In our case it helped to upgrade selenium.
